# Generated by Django 5.0.6 on 2024-06-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='заголовок')),
                ('slug', models.CharField(max_length=100)),
                ('content', models.TextField(verbose_name='содержимое статьи')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='post/photo', verbose_name='превью')),
                ('created_at', models.DateTimeField(verbose_name='дата создания')),
                ('is_published', models.BooleanField(verbose_name='признак публикации')),
                ('views_count', models.IntegerField(verbose_name='количество просмотров')),
            ],
            options={
                'verbose_name': 'пост',
                'verbose_name_plural': 'посты',
            },
        ),
    ]
