# Generated by Django 5.0.6 on 2024-06-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateField(blank=True, null=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product/photo', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateField(blank=True, null=True, verbose_name='дата изменения'),
        ),
    ]
